document.write('	<!--HEADER-->');
document.write('	<table height=122 width=900 border=0 cellpadding=0 cellspacing=0>');
document.write('	 <tr height=70><td width=386><a href=http://www.wescosports.com><img src=logo386x70.png border=0></a></td><td width=450></td></tr>');
document.write('	 <tr height=52>          <td><a href=http://www.wescosports.com><img src=logo386x52.jpg border=0></a></td>');
document.write('                     <td valign=middle>');
document.write('				<TABLE width=100% border=0 cellpadding=0 cellspacing=0>');
document.write('				<TR><TD width=26% align=left>');
//document.write('				<select name=teampages><option value="">Team Pages</option>');
//document.write('				<option value="">BBD</option>');
//document.write('				<option value="">New Fairfield</option>');
//document.write('				<option value="">Newtown</option>');
//document.write('				<option value="">Ridgefield</option>');
//document.write('				</select></TD>');
document.write('				<TD width=23% align=left>');
document.write('				<font face=calibri color=#ccccff>203.775.2227</font>');
document.write('                        </TD><TD width=38% align=center>      ');
document.write('<a href="#" onClick=window.open("emailquestionform.htm","EQwindow","location=1,status=1,scrollbars=1,width=720,height=540,resizable=no")><font face=calibri color=#ccccff>email@wescosports.com</a></font>');
document.write('				</TD><TD  width=13% align=right>      ');
document.write('   	     	            <a href="http://www.facebook.com/home.php?#/pages/Brookfield-CT/Wesco-Sports-Center/201665960345?ref=search&sid=100000691144314.1986643104..1" target="_blank"><img src=facebooklink.jpg border=0 alt="Wesco Facebook Page" align=absmiddle></a>&nbsp;');
document.write(' 			      </TD></TR>');
document.write('                        </TABLE>');
document.write('                     </td></tr>');
document.write('	</table>');
document.write('      <!--end HEADER-->');
